using System.Collections.Generic;
using BepInEx;
using Jotunn.Entities;
using Jotunn.Managers;
using UnityEngine;

namespace RtDBiomes                        
{
    internal partial class RtDBiomes : BaseUnityPlugin   
    {
        private CustomLocalization Localization;
        
        public void JSONSupport()
        {
            TextAsset[] textAssets = MyAssets.LoadAllAssets<TextAsset>();
            foreach (var textAsset in textAssets)
            {
                var lang = textAsset.name.Replace("_RtDBiomes.json", null);
                Localization.AddJsonFile(lang, textAsset.ToString());
            }
        }
        
        public void Localizations()
        {
            Localization = LocalizationManager.Instance?.GetLocalization();

            if (Localization == null)
            {
                Logger.LogError("Localization system not ready.");
                return;
            }
            
            Localization.AddTranslation("English", new Dictionary<string, string>
            {
                // AshLands Rocks
                { "AshLandsRock1_RtD", "Charred Rock" },
                { "AshLandsRock2_RtD", "Charred Rock" },
                { "AshLandsRock4_RtD", "Charred Rock" },
                { "AshLandsRock5_RtD", "Charred Rock" },
                { "AshLandsRock6_RtD", "Charred Rock" },
                // AshLands Bushes
                { "AshLandsBush1_RtD", "Dead Plant" },
                { "AshLandsPlantPiece1_RtD", "Dead Plant" },
                { "AshLandsBush2_RtD", "Dead Plant" },
                { "AshLandsBush3_RtD", "Dead Plant" },
                { "AshLandsBush4_RtD", "Dead Plant" },
                { "AshLandsBush5_RtD", "Dead Plant" },
                { "AshLandsBush6_RtD", "Dead Plant" },
                { "AshLandsBush7_RtD", "Dead Plant" },
                { "AshLandsBush8_RtD", "Dead Plant" },
                { "AshLandsBush9_RtD", "Dead Plant" },
                { "AshLandsBush10_RtD", "Dead Plant" },
                { "AshLandsBush11_RtD", "Dead Plant" },
                { "AshLandsBush12_RtD", "Dead Plant" },
                { "AshLandsBush13_RtD", "Dead Plant" },
                { "AshLandsBush14_RtD", "Dead Plant" },
                { "AshLandsBush15_RtD", "Dead Plant" },
                { "AshLandsBush16_RtD", "Dead Plant" },
                { "AshLandsBush17_RtD", "Dead Plant" },
                { "AshLandsBush18_RtD", "Dead Plant" },
                { "AshLandsBush19_RtD", "Dead Plant" },
                { "AshLandsBush20_RtD", "Dead Plant" },
                { "AshLandsBush21_RtD", "Dead Plant" },
                { "AshLandsBush22_RtD", "Dead Plant" },
                { "AshLandsBush23_RtD", "Dead Plant" },
                { "AshLandsBush24_RtD", "Dead Plant" },
                { "AshLandsBush25_RtD", "Dead Plant" },
                { "AshLandsBush26_RtD", "Dead Plant" },
                // BlackForest Bushes
                { "BlackForestBush1_RtD", "WildFlower" },
                { "BlackForestBush2_RtD", "WildFlower" },
                { "BlackForestBush3_RtD", "Bush" },
                { "BlackForestBush4_RtD", "Bush" },
                { "BlackForestBush5_RtD", "Bush" },
                { "BlackForestBush6_RtD", "Burdock" },
                { "BlackForestBush7_RtD", "Burdock" },
                { "BlackForestBush8_RtD", "Burdock" },
                { "ForestGreen1_RtD", "Evergreen Bush" },
                { "ForestGreen2_RtD", "Evergreen Bush" },
                { "ForestGreen3_RtD", "Evergreen Bush" },
                { "ForestGreen4_RtD", "Evergreen Bush" },
                // Dead Wood
                { "DeadWoodHalf", "Dead Log" },
                { "DeadWoodLog", "Dead Log" },
                { "DeadWoodStump", "Dead Stump" },
                { "DeadTree1_RtD", "Dead Tree" },
                { "DeadTree2_RtD", "Dead Tree" },
                { "DeadTree3_RtD", "Dead Tree" },
                { "DeadTree4_RtD", "Dead Tree" },
                { "DeadTree5_RtD", "Dead Tree" },
                { "DeadTree6_RtD", "Dead Tree" },
                { "DeadTree7_RtD", "Dead Tree" },
                { "DeadTree8_RtD", "Dead Tree" },
                { "DeadTree9_RtD", "Dead Tree" },
                // DeepNorth Bushes
                { "DeepNorthBush1_RtD", "WildFlower" },
                { "DeepNorthBush2_RtD", "WildFlower" },
                { "DeepNorthBush3_RtD", "WildFlower" },
                { "DeepNorthBush4_RtD", "WildFlower" },
                { "DeepNorthBush5_RtD", "WildFlower" },
                { "DeepNorthBush6_RtD", "WildFlower" },
                { "DeepNorthBush7_RtD", "WildFlower" },
                { "DeepNorthBush8_RtD", "WildFlower" },
                { "DeepNorthBush9_RtD", "WildFlower" },
                { "DeepNorthBush10_RtD", "WildFlower" },
                // DeepNorth Rocks
                { "DeepNorthRock1_RtD", "Icy Rock" },
                { "DeepNorthRock2_RtD", "Icy Rock" },
                { "DeepNorthRock4_RtD", "Icy Rock" },
                { "DeepNorthRock5_RtD", "Icy Rock" },
                { "DeepNorthRock6_RtD", "Icy Rock" },
                // Logs
                { "AcaciaLog", "Log" },
                { "AcaciaLogHalf", "Log" },
                { "BlossomLog", "Log" },
                { "BlossomLogHalf", "Log" },
                { "CottonWoodLog", "Log" },
                { "CottonWoodHalf", "Log" },
                { "OakWoodLog", "Log" },
                { "OakWoodHalf", "Log" },
                { "PineWoodHalf", "Log" },
                { "PineWoodLog", "Log" },
                { "PineWoodLog1", "Log" },
                // Forest Trees
                { "ForestTree1_RtD", "Maple Tree" },
                { "ForestTree2_RtD", "Maple Tree" },
                // Magic Logs & Stumps
                { "MagicLog1", "Log" },
                { "MagicLog2", "Log" },
                { "MagicLog3", "Log" },
                { "MagicLog6", "Log" },
                { "MagicLog7", "Log" },
                { "MagicLog8", "Log" },
                { "MagicLog9", "Log" },
                { "MagicLog10", "Log" },
                { "MagicStump1", "Stump" },
                { "MagicStump2", "Stump" },
                { "MagicStump3", "Stump" },
                { "MagicStump6", "Stump" },
                { "MagicStump7", "Stump" },
                { "MagicStump8", "Stump" },
                { "MagicStump9", "Stump" },
                { "MagicStump10", "Stump" },
                // Magic Trees
                { "MagicTree1_RtD", "Magic Tree" },
                { "MagicTree2_RtD", "Magic Tree" },
                { "MagicTree3_RtD", "Magic Tree" },
                { "MagicTree4_RtD", "Magic Tree" },
                { "MagicTree5_RtD", "Magic Tree" },
                { "MagicTree6_RtD", "Dead Tree" },
                { "MagicTree7_RtD", "Charred Tree" },
                { "MagicTree8_RtD", "Charred Tree" },
                { "MagicTree9_RtD", "Dead Tree" },
                { "MagicTree10_RtD", "Dead Tree" },
                { "MagicTreeSapling1_RtD", "Magic Sapling" },
                { "AshLandsSaplingD2_RtD", "Diseased Sapling" },
                { "FaeSeed_RtD", "Fae Seed" },
                { "FaeSeed_desc_RtD", "It pulses softly in your hand like a second heartbeat. Handle it wrong and the magic inside grows toward something you did not intend." },
                { "AshLandsSeed1_RtD", "Cinder Seed" },
                { "AshLandsSeed1_desc_RtD", "Plant it and something will grow. Something with fire in its roots and contempt for the soil it came from." },
                // Meadows Bushes
                { "MeadowsBush1_RtD", "Magical Flower" },
                { "MeadowsBush2_RtD", "Magical Flower" },
                { "MeadowsBush3_RtD", "Magical Flower" },
                { "MeadowsBush4_RtD", "Magical Flower" },
                { "MeadowsBush5_RtD", "Magical Flower" },
                { "MeadowsShroom1_RtD", "Large Mushroom" },
                { "MeadowsShroom2_RtD", "Large Mushroom" },
                { "MeadowsShroom3_RtD", "Large Mushroom" },
                { "MeadowsShroom4_RtD", "Large Mushroom" },
                { "MeadowsBush01_RtD", "Strange Plant" },
                { "MeadowsBush02_RtD", "Strange Plant" },
                { "MeadowsBush03_RtD", "Strange Plant" },
                { "MeadowsBush04_RtD", "Sapling" },
                { "MeadowsBush05_RtD", "Bush" },
                { "MeadowsBush06_RtD", "Bush" },
                { "SmallBush_RtD", "Bush" },
                // Mistlands Bushes
                { "MistLandsBush1_RtD", "Strange Plant" },
                { "MistLandsBush2_RtD", "Strange Plant" },
                { "MistLandsBush3_RtD", "Strange Plant" },
                { "MistLandsBush4_RtD", "Strange Plant" },
                { "MistLandsBush5_RtD", "Strange Plant" },
                { "MistLandsBush6_RtD", "Magical Flower" },
                { "MistLandsBush7_RtD", "Strange Plant" },
                // Yggdrasil
                { "ShootStump_RtD", "Yggdrasil Stump" },
                { "YggaShoot_Log_RtD", "Yggdrasil Log" },
                { "YggaShoot_LogHalf_RtD", "Yggdrasil Log" },
                { "YggdrasilTree1_RtD", "Yggdrasil" },
                { "YggdrasilTree2_RtD", "Yggdrasil" },
                // Evergreens
                { "EverGreen1_RtD", "Evergreen Bush" },
                { "EverGreen2_RtD", "Evergreen Bush" },
                { "EverGreen3_RtD", "Evergreen Bush" },
                { "EverGreen4_RtD", "Evergreen Bush" },
                // Mountain Bushes
                { "MountainBush1_RtD", "Winter WildFlower" },
                { "MountainBush2_RtD", "Winter WildFlower" },
                { "MountainBush3_RtD", "Winter WildFlower" },
                // Mushrooms
                { "RedShroom1_RtD", "Giant Mushroom" },
                { "RedShroom2_RtD", "Giant Mushroom" },
                { "RedShroom3_RtD", "Giant Mushroom" },
                { "RedShroom4_RtD", "Giant Mushroom" },
                { "BlackShroom1_RtD", "Giant Mushroom" },
                { "BlackShroom2_RtD", "Giant Mushroom" },
                { "BlackShroom3_RtD", "Giant Mushroom" },
                { "BlackShroom4_RtD", "Giant Mushroom" },
                { "BlueShroom1_RtD", "Giant Mushroom" },
                { "BlueShroom2_RtD", "Giant Mushroom" },
                { "BlueShroom3_RtD", "Giant Mushroom" },
                { "BlueShroom4_RtD", "Giant Mushroom" },
                { "YellowShroom1_RtD", "Giant Mushroom" },
                { "YellowShroom2_RtD", "Giant Mushroom" },
                { "YellowShroom3_RtD", "Giant Mushroom" },
                { "YellowShroom4_RtD", "Giant Mushroom" },
                { "GreenShroom1_RtD", "Giant Mushroom" },
                { "GreenShroom2_RtD", "Giant Mushroom" },
                { "GreenShroom3_RtD", "Giant Mushroom" },
                { "GreenShroom4_RtD", "Giant Mushroom" },
                // Palm Trees
                { "PalmLog", "Log" },
                { "PalmLogHalf", "Log" },
                { "PalmStump", "Log" },
                { "PalmTree1_RtD", "Palm Tree" },
                { "PalmTree2_RtD", "Palm Tree" },
                // Acacia
                { "Acacia4_RtD", "Acacia Tree" },
                { "AcaciaLog4", "Log" },
                { "AcaciaStump4", "Stump" },
                // Plains Bushes
                { "PlainsBush4_RtD", "Bamboo" },
                { "PlainsBush5_RtD", "Bamboo" },
                { "PlainsBush6_RtD", "Bamboo" },
                { "PlainsBush7_RtD", "Bamboo" },
                { "PlainsBush8_RtD", "Bamboo" },
                { "Acacia1_RtD", "Acacia Tree" },
                { "Acacia2_RtD", "Acacia Tree" },
                { "Acacia3_RtD", "Acacia Tree" },
                // Blossom Trees
                { "Blossom1_RtD", "Flowering DogWood" },
                { "Blossom2_RtD", "Flowering DogWood" },
                { "Blossom3_RtD", "Flowering DogWood" },
                { "Blossom4_RtD", "Flowering DogWood" },
                { "Blossom5_RtD", "Flowering DogWood" },
                // Other Trees
                { "CottonWood1_RtD", "Cotton Wood" },
                { "CottonWood2_RtD", "Cotton Wood" },
                { "Oak1_RtD", "Red Oak" },
                { "Oak2_RtD", "Red Oak" },
                { "RedPine_RtD", "Red Pine" },
                { "ThinPine1_RtD", "Winter Pine" },
                { "ThinPine2_RtD", "Winter Pine" },
                { "WinterPine1_RtD", "Winter Pine" },
                { "WinterPine2_RtD", "Winter Pine" },
                { "WinterPine3_RtD", "Winter Pine" },
                { "WinterPine4_RtD", "Winter Pine" },
                { "WinterPine5_RtD", "Winter Pine" },
                // Stumps
                { "AcaciaStump", "Stump" },
                { "BlossomStump", "Stump" },
                { "CottonWoodStump", "Stump" },
                { "OakWoodStump", "Stump" },
                { "PineWoodStump", "Stump" },
                // Swamp Bushes
                { "SwampBush1_RtD", "Rotting Sapling" },
                { "SwampBush2_RtD", "Rotting Sapling" },
                { "SwampBush3_RtD", "Strange Plant" },
                { "SwampBush4_RtD", "Strange Plant" },
                { "SwampBush5_RtD", "Strange Plant" },
                { "SwampBush6_RtD", "Strange Plant" },
                { "SwampBush7_RtD", "Strange Plant" },
                { "SwampBush8_RtD", "Strange Plant" },
                { "SwampBush9_RtD", "Strange Plant" },
                { "SwampBush10_RtD", "Strange Plant" },
                { "SwampBush11_RtD", "Strange Plant" },
                { "SwampBush12_RtD", "Death Bush" },
                { "SwampBush13_RtD", "Death Bush" },
                { "SwampBush14_RtD", "Death Bush" },
                { "SwampWoodHalf", "Log" },
                { "SwampWoodLog", "Log" },
                // Swamp Trees
                { "SwampTree1_RtD", "Ancient Tree" },
                { "SwampTree2_RtD", "Ancient Tree" },
                { "SwampTree3_RtD", "Ancient Tree" },
                { "SwampTree4_RtD", "Ancient Tree" },
                { "SwampTree5_RtD", "Ancient Tree" },
                { "SwampTree6_RtD", "Ancient Tree" },
                // Dead Ivy
                { "DeadIvy1_RtD", "Dead Ivy" },
                { "DeadIvy2_RtD", "Dead Ivy" },
                // Willow
                { "WillowLog", "Log" },
                { "WillowLogHalf", "Log" },
                { "WillowStump", "Stump" },
                { "SwampWoodStump", "Stump" },
                { "SwampWoodStump1", "Stump" },
                { "WillowTree1_RtD", "Willow Tree" },
                { "WillowTree2_RtD", "Willow Tree" },
                // Mountain Mushrooms
                { "MountainShroom1_RtD", "Giant Mushroom" },
                { "MountainShroom2_RtD", "Giant Mushroom" },
                { "MountainShroom3_RtD", "Giant Mushroom" },
                { "MountainShroom4_RtD", "Giant Mushroom" },
                // Seeds
                { "AcaciaSeeds_RtD", "Acacia Seeds" },
                { "AcaciaSeeds_desc_RtD", "Used to plant Acacia Trees" },
                { "BlossomSeeds_RtD", "DogWood Seeds" },
                { "BlossomSeeds_desc_RtD", "Used to plant DogWood Trees" },
                { "CottonWoodSeeds_RtD", "CottonWood Seeds" },
                { "CottonWoodSeeds_desc_RtD", "Used to plant CottonWood Trees" },
                { "OakWoodSeeds_RtD", "Acorns" },
                { "OakWoodSeeds_desc_RtD", "Used to plant OakWood Trees" },
                { "PalmTreeSeeds_RtD", "Well its not a Coconut.." },
                { "PalmTreeSeeds_desc_RtD", "Used to plant Palm Trees" },
                { "RedPineSeeds_RtD", "Red PineCone" },
                { "RedPineSeeds_desc_RtD", "Used to Red Pine Trees" },
                { "ThinPineSeeds_RtD", "Green PineCone" },
                { "ThinPineSeeds_desc_RtD", "Used to plant more Pine Trees" },
                { "WillowSeeds_RtD", "Willow Tree Seed" },
                { "WillowSeeds_desc_RtD", "Used to plant Willow Trees" },
                { "WinterPineSeeds1_RtD", "Winter PineCone" },
                { "WinterPineSeeds1_desc_RtD", "Used to plant Winter Pine Trees" },
                { "WinterPineSeeds2_RtD", "Frosty PineCone" },
                { "WinterPineSeeds2_desc_RtD", "Used to plant Winter Pine Trees" },
                { "DeepNorthRock4_frac_RtD", "Its a rock, what did you expect?" },
                { "DeepNorthRock5_frac_RtD", "Its a rock, what did you expect?" },
                // Plant Seeds
                { "PlantSeedAshLands_RtD", "AshLands Seed" },
                { "PlantSeedAshLands_desc_RtD", "A seed to plant all AshLands plants." },
                { "PlantSeedBlackForest_RtD", "BlackForest Seed" },
                { "PlantSeedBlackForest_desc_RtD", "A seed to plant all BlackForest plants." },
                { "PlantSeedDeepNorth_RtD", "DeepNorth Seed" },
                { "PlantSeedDeepNorth_desc_RtD", "A seed to plant all DeepNorth plants." },
                { "PlantSeedMeadows_RtD", "Meadows Seed" },
                { "PlantSeedMeadows_desc_RtD", "A seed to plant all Meadows plants." },
                { "PlantSeedMistlands_RtD", "Mistlands Seed" },
                { "PlantSeedMistlands_desc_RtD", "A seed to plant all Mistlands plants." },
                { "PlantSeedMountain_RtD", "Mountain Seed" },
                { "PlantSeedMoutain_desc_RtD", "A seed to plant all Mountain plants." },
                { "PlantSeedPlains_RtD", "Plains Seed" },
                { "PlantSeedPlains_desc_RtD", "A seed to plant all Plains plants." },
                { "PlantSeedSwamp_RtD", "Swamp Seed" },
                { "PlantSeedSwamp_desc_RtD", "A seed to plant all Swamp plants." },
                { "MapleSeed_RtD", "Maple Seed" },
                { "MapleSeed_desc", "Used for planting" },
                { "AshLandsSeed2_RtD", "AshSeed" },
                { "AshLandsSeed2_desc_RtD", "Used for planting" },
                // Small Pines
                { "RedPineSmall1_RtD", "Red Pine" },
                { "RedPineSmall2_RtD", "Red Pine" },
                { "RedPineSmall3_RtD", "Red Pine" },
                { "RedPineSmall4_RtD", "Red Pine" },
                { "RedPineSmall5_RtD", "Red Pine" },
                // Saplings
                { "AcaciaSapling_RtD", "Acacia Sapling" },
                { "BlossomSapling_RtD", "DogWood Sapling" },
                { "CottonWoodSapling_RtD", "CottonWood Sapling" },
                { "OakSapling_RtD", "OakWood Sapling" },
                { "PalmTreeSapling_RtD", "Palm Sapling" },
                { "RedPineSapling_RtD", "RedPine Sapling" },
                { "ThinPineSapling_RtD", "GreenPine Sapling" },
                { "WillowSapling_RtD", "Willow Sapling" },
                { "WinterPineSapling1_RtD", "WinterPine Sapling" },
                { "WinterPineSapling2_RtD", "WinterPine Sapling" },
                { "MapleSapling1_RtD", "Maple Sapling" },
                { "MapleSapling2_RtD", "Maple Sapling" },
                { "SwampSapling1_RtD", "Diseased Sapling" },
                { "SwampSapling2_RtD", "Diseased Sapling" },
                { "Sapling1P_RtD", "Small Tree" },
                { "Sapling2P_RtD", "Small Tree" },
                { "AshLandsSaplingD1_RtD", "Diseased Sapling" },
                { "AshLandsSaplingD3_RtD", "Diseased Sapling" },
                // Vines - Blue
                { "IvyWallCD_1_FB_RtD", "Vines Blue" },
                { "IvyWallCD_2_FB_RtD", "Vines Blue" },
                { "IvyWallD_1_FB_RtD", "Vines Blue" },
                { "IvyWallD_2_FB_RtD", "Vines Blue" },
                { "IvyWallD_3_FB_RtD", "Vines Blue" },
                { "IvyWallD_4_FB_RtD", "Vines Blue" },
                { "IvyWallD_5_FB_RtD", "Vines Blue" },
                { "IvyWallD_6_FB_RtD", "Vines Blue" },
                { "IvyWallU_1_FB_RtD", "Vines Blue" },
                { "IvyWallU_2_FB_RtD", "Vines Blue" },
                { "IvyWallU_3_FB_RtD", "Vines Blue" },
                { "IvyWallU_4_FB_RtD", "Vines Blue" },
                { "IvyWallWD_1_FB_RtD", "Vines Blue" },
                { "IvyWallWD_2_FB_RtD", "Vines Blue" },
                // Vines - Lt Pink
                { "IvyWallD_1_FC_RtD", "Vines Lt Pink" },
                { "IvyWallD_2_FC_RtD", "Vines Lt Pink" },
                { "IvyWallD_3_FC_RtD", "Vines Lt Pink" },
                { "IvyWallD_4_FC_RtD", "Vines Lt Pink" },
                { "IvyWallD_5_FC_RtD", "Vines Lt Pink" },
                { "IvyWallD_6_FC_RtD", "Vines Lt Pink" },
                // Vines - Gold
                { "IvyWallD_1_FE_RtD", "Vines Gold" },
                { "IvyWallD_2_FE_RtD", "Vines Gold" },
                { "IvyWallD_3_FE_RtD", "Vines Gold" },
                { "IvyWallD_4_FE_RtD", "Vines Gold" },
                { "IvyWallD_5_FE_RtD", "Vines Gold" },
                { "IvyWallD_6_FE_RtD", "Vines Gold" },
                { "IvyWallU_1_FE_RtD", "Vines Gold" },
                { "IvyWallU_2_FE_RtD", "Vines Gold" },
                { "IvyWallU_3_FE_RtD", "Vines Gold" },
                { "IvyWallU_4_FE_RtD", "Vines Gold" },
                { "IvyWallWD_1_FE_RtD", "Vines Gold" },
                { "IvyWallWD_2_FE_RtD", "Vines Gold" },
                // Vines - Dark Pink
                { "IvyWallD_1_FP_RtD", "Vines Dark Pink" },
                { "IvyWallD_2_FP_RtD", "Vines Dark Pink" },
                { "IvyWallD_3_FP_RtD", "Vines Dark Pink" },
                { "IvyWallD_4_FP_RtD", "Vines Dark Pink" },
                { "IvyWallD_5_FP_RtD", "Vines Dark Pink" },
                { "IvyWallD_6_FP_RtD", "Vines Dark Pink" },
                { "IvyWallU_1_FP_RtD", "Vines Dark Pink" },
                { "IvyWallU_2_FP_RtD", "Vines Dark Pink" },
                { "IvyWallU_3_FP_RtD", "Vines Dark Pink" },
                { "IvyWallU_4_FP_RtD", "Vines Dark Pink" },
                { "IvyWallWD_1_FP_RtD", "Vines Dark Pink" },
                { "IvyWallWD_2_FP_RtD", "Vines Dark Pink" },
                // Vines - Red
                { "IvyWallD_1_FR_RtD", "Vines Red" },
                { "IvyWallD_2_FR_RtD", "Vines Red" },
                { "IvyWallD_3_FR_RtD", "Vines Red" },
                { "IvyWallD_4_FR_RtD", "Vines Red" },
                { "IvyWallD_5_FR_RtD", "Vines Red" },
                { "IvyWallD_6_FR_RtD", "Vines Red" },
                { "IvyWallU_1_FR_RtD", "Vines Red" },
                { "IvyWallU_2_FR_RtD", "Vines Red" },
                { "IvyWallU_3_FR_RtD", "Vines Red" },
                { "IvyWallU_4_FR_RtD", "Vines Red" },
                { "IvyWallWD_1_FR_RtD", "Vines Red" },
                { "IvyWallWD_2_FR_RtD", "Vines Red" },
                // Vines - Floor
                { "IvyFloor_1_FS_RtD", "Floor Vines Large" },
                { "IvyFloor_2_FS_RtD", "Floor Vines Long" },
                { "IvyFloor_3_FS_RtD", "Floor Vines Small" },
                { "IvyFloor_4_FS_RtD", "Floor Vines Extra Small" },
                // Vines - Gold Purple
                { "IvyWallD_1_FS_RtD", "Vines Gold Purple" },
                { "IvyWallD_2_FS_RtD", "Vines Gold Purple" },
                { "IvyWallD_3_FS_RtD", "Vines Gold Purple" },
                { "IvyWallD_4_FS_RtD", "Vines Gold Purple" },
                { "IvyWallD_5_FS_RtD", "Vines Gold Purple" },
                { "IvyWallD_6_FS_RtD", "Vines Gold Purple" },
                { "IvyWallU_1_FS_RtD", "Vines Gold Purple" },
                { "IvyWallU_2_FS_RtD", "Vines Gold Purple" },
                { "IvyWallU_3_FS_RtD", "Vines Gold Purple" },
                { "IvyWallU_4_FS_RtD", "Vines Gold Purple" },
                { "IvyWallWD_1_FS_RtD", "Vines Gold Purple" },
                { "IvyWallWD_2_FS_RtD", "Vines Gold Purple" },
                // Vines - Gold Lt Purple
                { "IvyWallD_1_FV_RtD", "Vines Gold Lt Purple" },
                { "IIvyWallD_2_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallD_3_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallD_4_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallD_5_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallD_6_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallU_1_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallU_2_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallU_3_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallU_4_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallWD_1_FV_RtD", "Vines Gold Lt Purple" },
                { "IvyWallWD_2_FV_RtD", "Vines Gold Lt Purple" },
                // Vines - No Flower
                { "IvyWallD_1_RtD", "Vines No Flower" },
                { "IvyWallD_2_RtD", "Vines No Flower" },
                { "IvyWallD_3_RtD", "Vines No Flower" },
                { "IvyWallD_4_RtD", "Vines No Flower" },
                { "IvyWallD_5_RtD", "Vines No Flower" },
                { "IvyWallD_6_RtD", "Vines No Flower" },
                { "IvyWallU_1_RtD", "Vines No Flower" },
                { "IvyWallU_2_RtD", "Vines No Flower" },
                { "IvyWallU_3_RtD", "Vines No Flower" },
                { "IvyWallU_4_RtD", "Vines No Flower" },
                // Placeable Plants - AshLands
                { "AshLandsBush1P_RtD", "Diseased Plant" },
                { "AshLandsBush2P_RtD", "Diseased Plant" },
                { "AshLandsBush3P_RtD", "Cactus" },
                { "AshLandsBush4P_RtD", "Cactus" },
                { "AshLandsBush5P_RtD", "Diseased Plant" },
                { "AshLandsBush6P_RtD", "Diseased Plant" },
                { "AshLandsBush7P_RtD", "Diseased Plant" },
                { "AshLandsBush8P_RtD", "Diseased Plant" },
                { "AshLandsBush9P_RtD", "Diseased Plant" },
                { "AshLandsBush10P_RtD", "Diseased Plant" },
                { "AshLandsBush11P_RtD", "Diseased Plant" },
                { "AshLandsBush12P_RtD", "Diseased Plant" },
                { "AshLandsBush13P_RtD", "Diseased Plant" },
                { "AshLandsBush14P_RtD", "Diseased Plant" },
                { "AshLandsBush15P_RtD", "Diseased Plant" },
                { "AshLandsBush16P_RtD", "Diseased Plant" },
                { "AshLandsBush17P_RtD", "Cactus" },
                { "AshLandsBush18P_RtD", "Cactus" },
                { "AshLandsBush19P_RtD", "Cactus" },
                { "AshLandsBush20P_RtD", "Cactus" },
                { "AshLandsBush21P_RtD", "Cactus" },
                { "AshLandsBush22P_RtD", "Cactus" },
                { "AshLandsBush23P_RtD", "Cactus" },
                { "AshLandsBush24P_RtD", "Cactus" },
                { "AshLandsBush25P_RtD", "Cactus" },
                { "AshLandsBush26P_RtD", "Cactus" },
                // Placeable Plants - BlackForest
                { "BlackForestBush1P_RtD", "Flower" },
                { "BlackForestBush2P_RtD", "Flower" },
                { "BlackForestBush3P_RtD", "Bush" },
                { "BlackForestBush4P_RtD", "Bush" },
                { "BlackForestBush5P_RtD", "Bush" },
                { "BlackForestBush6P_RtD", "Burdock" },
                { "BlackForestBush7P_RtD", "Burdock" },
                { "BlackForestBush8P_RtD", "Burdock" },
                { "BlackForestBush9P_RtD", "EverGreen Bush" },
                { "BlackForestBush10P_RtD", "EverGreen Bush" },
                { "BlackForestBush11P_RtD", "EverGreen Bush" },
                { "BlackForestBush12P_RtD", "EverGreen Bush" },
                // Placeable Plants - DeepNorth
                { "DeepNorthBush1P_RtD", "Wild Flower" },
                { "DeepNorthBush2P_RtD", "Wild Flower" },
                { "DeepNorthBush3P_RtD", "Wild Flower" },
                { "DeepNorthBush4P_RtD", "Wild Flower" },
                { "DeepNorthBush5P_RtD", "Wild Flower" },
                { "DeepNorthBush6P_RtD", "Wild Flower" },
                { "DeepNorthBush7P_RtD", "Wild Flower" },
                { "DeepNorthBush8P_RtD", "Wild Flower" },
                { "DeepNorthBush9P_RtD", "Wild Flower" },
                { "DeepNorthBush10P_RtD", "Wild Flower" },
                // Placeable Plants - Meadows
                { "MeadowsBush1P_RtD", "Wild Flower" },
                { "MeadowsBush2P_RtD", "Wild Flower" },
                { "MeadowsBush3P_RtD", "Wild Flower" },
                { "MeadowsBush4P_RtD", "Wild Flower" },
                { "MeadowsBush5P_RtD", "Wild Flower" },
                { "MeadowsBush01P_RtD", "Plant" },
                { "MeadowsBush02P_RtD", "Plant" },
                { "MeadowsBush03P_RtD", "Plant" },
                { "MeadowsBush04P_RtD", "Plant" },
                { "MeadowsBush05P_RtD", "Plant" },
                { "MeadowsBush06P_RtD", "Plant" },
                { "SmallBushP_RtD", "Bush" },
                // Placeable Plants - Mistlands
                { "MistLandsBush1P_RtD", "Strange Plant" },
                { "MistLandsBush2P_RtD", "Strange Plant" },
                { "MistLandsBush3P_RtD", "Strange Plant" },
                { "MistLandsBush4P_RtD", "Strange Plant" },
                { "MistLandsBush5P_RtD", "Strange Plant" },
                { "MistLandsBush6P_RtD", "Wild Flower" },
                { "MistLandsBush7P_RtD", "Plant" },
                // Placeable Plants - Evergreens
                { "EverGreen1P_RtD", "EverGreen" },
                { "EverGreen2P_RtD", "EverGreen" },
                { "EverGreen3P_RtD", "EverGreen" },
                { "EverGreen4P_RtD", "EverGreen" },
                // Placeable Plants - Mountain
                { "MountainBush1P_RtD", "Wild Flower" },
                { "MountainBush2P_RtD", "Wild Flower" },
                { "MountainBush3P_RtD", "Wild Flower" },
                // Placeable Plants - Plains
                { "PlainsBush1P_RtD", "CloudBerry Bush" },
                { "PlainsBush2P_RtD", "CloudBerry Bush" },
                { "PlainsBush3P_RtD", "CloudBerry Bush" },
                { "PlainsBush4P_RtD", "Bamboo" },
                { "PlainsBush5P_RtD", "Bamboo" },
                { "PlainsBush6P_RtD", "Bamboo" },
                { "PlainsBush7P_RtD", "Bamboo" },
                { "PlainsBush8P_RtD", "Bamboo" },
                // Placeable Plants - Swamp
                { "DeadIvy1P_RtD", "Dead Ivy" },
                { "DeadIvy2P_RtD", "Dead Ivy" },
                { "SwampBush1P_RtD", "Rotting Plant" },
                { "SwampBush2P_RtD", "Rotting Plant" },
                { "SwampBush3P_RtD", "Wild Flower" },
                { "SwampBush4P_RtD", "Plant" },
                { "SwampBush5P_RtD", "Wild Flower" },
                { "SwampBush6P_RtD", "Wild Flower" },
                { "SwampBush7P_RtD", "Wild Flower" },
                { "SwampBush8P_RtD", "Plant" },
                { "SwampBush9P_RtD", "Plant" },
                { "SwampBush10P_RtD", "Plant" },
                { "SwampBush11P_RtD", "Plant" },
                { "SwampBush12P_RtD", "Dead Bush" },
                { "SwampBush13P_RtD", "Dead Bush" },
                { "SwampBush14P_RtD", "Dead Bush" },
                // Placeable Mushrooms
                { "BlackShroom1P_RtD", "Mushroom" },
                { "BlackShroom2P_RtD", "Mushroom" },
                { "BlackShroom3P_RtD", "Mushroom" },
                { "BlackShroom4P_RtD", "Mushroom" },
                { "BlueShroom1P_RtD", "Mushroom" },
                { "BlueShroom2P_RtD", "Mushroom" },
                { "BlueShroom3P_RtD", "Mushroom" },
                { "BlueShroom4P_RtD", "Mushroom" },
                { "GreenShroom1P_RtD", "Mushroom" },
                { "GreenShroom2P_RtD", "Mushroom" },
                { "GreenShroom3P_RtD", "Mushroom" },
                { "GreenShroom4P_RtD", "Mushroom" },
                { "MeadowsShroom1P_RtD", "Mushroom" },
                { "MeadowsShroom2P_RtD", "Mushroom" },
                { "MeadowsShroom3P_RtD", "Mushroom" },
                { "MeadowsShroom4P_RtD", "Mushroom" },
                { "MountainShroom1P_RtD", "Mushroom" },
                { "MountainShroom2P_RtD", "Mushroom" },
                { "MountainShroom3P_RtD", "Mushroom" },
                { "MountainShroom4P_RtD", "Mushroom" },
                { "RedShroom1P_RtD", "Mushroom" },
                { "RedShroom2P_RtD", "Mushroom" },
                { "RedShroom3P_RtD", "Mushroom" },
                { "RedShroom4P_RtD", "Mushroom" },
                { "YellowShroom1P_RtD", "Mushroom" },
                { "YellowShroom2P_RtD", "Mushroom" },
                { "YellowShroom3P_RtD", "Mushroom" },
                { "YellowShroom4P_RtD", "Mushroom" },
                // Pickables
                { "CloudberryBush_RtD", "Cloudberry Bush" },
                { "GlowingMushroom_RtD", "Glowing Mushroom" },
                { "Pickable_Dandelion_RtD", "Dandelion" },
                { "Pickable_Mushroom_RtD", "Mushroom" },
                { "Pickable_Mushroom_yellow_RtD", "Yellow Mushroom" },
                { "Pickable_Thistle_RtD", "Thistle" },
                { "BlueberryBush_RtD", "Blueberry Bush" },
                { "Bush01_heath_RtD", "Heath Bush" },
                { "Bush01_RtD", "Bush" },
                { "Bush02_en_RtD", "Bush" },
                { "FirTree_small_dead_RtD", "Dead Fir" },
                { "RaspberryBush_RtD", "Raspberry Bush" },
                { "shrub_2_heath_RtD", "Heath Shrub" },
                { "shrub_2_RtD", "Shrub" },
                { "Pickable_Flint_RtD", "Pickable Flint" },
                { "Pickable_Stone_RtD", "Pickable Stone" },
                { "RedFirSmallPlant_RtD", "Red Fir" }
            });
        }
    }
}